Sprint4
ClevertecFrontendLab/liahrothstein pull request #2
Opened 2023-02-25 14:37 UTC by liahrothstein

2023-02-25 14:43 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 6%.
Общее количество тестов: 16.
Количество непройденных тестов: 15.

2023-02-26 14:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 56%.
Общее количество тестов: 16.
Количество непройденных тестов: 7.

2023-02-26 19:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 62%.
Общее количество тестов: 16.
Количество непройденных тестов: 6.

2023-02-26 21:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 16.
Количество непройденных тестов: 4.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1677445455/search-result-not-found.png)

2023-02-27 05:47 UTC, Ivan6813 requested changes

2023-02-27 05:47 UTC, Ivan6813 commented on src/components/all-books/all-books.css
>      font-weight: 700;
при фокусе на инпуте иконка лупы должна иметь другой цвет, сверься с макетом

![msedge_2goYTXmVIq](https://user-images.githubusercontent.com/79784960/221484392-115c2dd6-4260-4be6-9469-bf77348592c9.png)

2023-02-27 08:32 UTC, Ivan6813 approved these changes

2023-02-27 08:32 UTC, Ivan6813 commented on package.json
>    },
ставлю апрув, так как заканчивается прием работ в 12. Я тебе написал одно замечание, исправишь его уже в следующем спринте

2023-02-27 09:36 UTC, merged